---
# find all the data you want from there AZ Cli commands:
# az vm image list --offer CentOS7/WindowsServer --all --output table
# az vm list-sizes --location eastus --output table
# the 'infra' tree is built as a 'map', as golang VIPER lib supports only 'map' subtree 
config : 
 cloud : azure 
 infra : # list of infra config stacks 
    azure_centos7_Standard_DS4_v2:
      region: westus
      type  : Standard_DS4_v2
      image : tidalmediainc:centos-7-8-minimal:centos-7-minimal:1.0.2 # reqd: az vm image terms accept --urn "perforce:centos7:7:7.9.2022060800"
      disk  : [128 256] # multiple sizes allowed 
      tags: 
         - project: myproject
           group  : tse 
    azure_centos7_Standard_DS2_v2:
      region: westus
      type  : Standard_DS2_v2
      image : tidalmediainc:centos-7-8-minimal:centos-7-minimal:1.0.2 # reqd: az vm image terms accept --urn "perforce:centos7:7:7.9.2022060800"
      disk  : [ 128 ] # multiple sizes allowed 
      tags: 
         - project: myproject2
           group  : tse
           costcenter: sales 
